/* tslint:disable */
/* eslint-disable */
/**
 * SmartSwap Backend API
 * Production-ready REST API for minimal CEX/DEX backend, in-memory orderbook, swap simulation, and quoting. Designed for low-latency and extensibility. All amounts and prices are strings (decimals) for precise compatibility with DeFi and frontend logic. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Response when order is added
 * @export
 * @interface AddOrderResponse
 */
export interface AddOrderResponse {
    /**
     * Unique order UUID
     * @type {string}
     * @memberof AddOrderResponse
     */
    orderId?: string;
    /**
     * Operation result
     * @type {string}
     * @memberof AddOrderResponse
     */
    status?: string;
}

/**
 * Check if a given object implements the AddOrderResponse interface.
 */
export function instanceOfAddOrderResponse(value: object): value is AddOrderResponse {
    return true;
}

export function AddOrderResponseFromJSON(json: any): AddOrderResponse {
    return AddOrderResponseFromJSONTyped(json, false);
}

export function AddOrderResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AddOrderResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'orderId': json['order_id'] == null ? undefined : json['order_id'],
        'status': json['status'] == null ? undefined : json['status'],
    };
}

export function AddOrderResponseToJSON(json: any): AddOrderResponse {
    return AddOrderResponseToJSONTyped(json, false);
}

export function AddOrderResponseToJSONTyped(value?: AddOrderResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'order_id': value['orderId'],
        'status': value['status'],
    };
}

