/* tslint:disable */
/* eslint-disable */
/**
 * SmartSwap Backend API
 * Production-ready REST API for minimal CEX/DEX backend, in-memory orderbook, swap simulation, and quoting. Designed for low-latency and extensibility. All amounts and prices are strings (decimals) for precise compatibility with DeFi and frontend logic. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DeleteOrderRequest
 */
export interface DeleteOrderRequest {
    /**
     * Order UUID to delete
     * @type {string}
     * @memberof DeleteOrderRequest
     */
    id: string;
}

/**
 * Check if a given object implements the DeleteOrderRequest interface.
 */
export function instanceOfDeleteOrderRequest(value: object): value is DeleteOrderRequest {
    if (!('id' in value) || value['id'] === undefined) return false;
    return true;
}

export function DeleteOrderRequestFromJSON(json: any): DeleteOrderRequest {
    return DeleteOrderRequestFromJSONTyped(json, false);
}

export function DeleteOrderRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeleteOrderRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
    };
}

export function DeleteOrderRequestToJSON(json: any): DeleteOrderRequest {
    return DeleteOrderRequestToJSONTyped(json, false);
}

export function DeleteOrderRequestToJSONTyped(value?: DeleteOrderRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
    };
}

